# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: inoy_618闪购红包雨+特物国创IP+泡泡作战

on:
  workflow_dispatch:
  schedule:
    - cron: '52 15 * * *'
  repository_dispatch:
    types: jd_dphby.js
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
   
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js 15.x
       uses: actions/setup-node@v1
       with:
           node-version: 15.x 
     - name: npm install
       run: |
          npm install
     - name: '运行 【app】'
       run: |
          curl https://raw.githubusercontent.com/inoyna11/jd28/master/jd_dphby.js -o jd_dphby.js
          node jd_dphby.js
          curl https://raw.githubusercontent.com/inoyna11/jd28/master/jd_gcip.js -o jd_gcip.js
          node jd_gcip.js
          curl https://raw.githubusercontent.com/inoyna11/jd28/master/jd_ppdz.js -o jd_ppdz.js
          node jd_ppdz.js
          #curl https://raw.githubusercontent.com/inoyna11/jd28/master/jd_ry618.js -o jd_ry618.js
          #node jd_ry618.js
          
          
       env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          QQ_SKEY: ${{ secrets.QQ_SKEY }}
          QQ_MODE: ${{ secrets.QQ_MODE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ github.event.client_payload.PUSH_PLUS_USER || secrets.PUSH_PLUS_USER }}
